version: '3.3'

services:
    postgres:
      image: postgres:13
      enviroment:
        - POSTGRES_DB=nest-training
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      ports: 5432:5432
      volumes:
        - ./postgres_data:/var/lib/postgresql/data

    mysql:
      image: mysql:5
      enviroment:
        - MYSQL_DATABASE=nest-training
        - MYSQL_USER=root
        - MYSQL_ROOT_PASSWORD=123456
      ports: 3306:3306
      volumes:
        - ./mysql_data:/var/lib/mysql